import { IFS, radial } from '../../src/ifs';
import { LSystem } from '../../src/l';
import type { FractalType } from '../types';
import { renderFractalImage } from './server-render-algos';
import type { AnyRecord, Rgb } from './server-render-utils';
import {
  IFS_MATRIX_PALETTE,
  createTransform,
  gradientColor,
  parseColor,
  parseRules,
} from './server-render-utils';

const MAX_IFS_POINTS_TEX = 12_000;
const MAX_RASTER_DOTS = 30_000;
const DEFAULT_TEX_INTERNAL_RASTER = 320;
/** pdfTeX input buffer (~200k); keep generated lines well under to avoid "bufsize" errors. */
const MAX_TEX_SOURCE_LINE_CHARS = 100_000;

function rgbToTikz(rgb258: Rgb): string {
  const [r, g, b] = rgb258;
  return `{rgb,255:red,${r};green,${g};blue,${b}}`;
}

function escapeTikzComment(s: string): string {
  return s.replace(/%/g, '\\%').replace(/\n/g, ' ');
}

/**
 * Each `\\fill ... circle` is wrapped in `\\pgfinterruptpath ... \\endpgfinterruptpath` so TikZ/PGF
 * does not merge thousands of circles into one unbounded soft path (`\\pgf@last@processed@path`),
 * which exhausts pdfTeX main memory. `\\begin{scope}` alone does not prevent that.
 */
function emitPointCircleFills(
  body: string[],
  pts: Array<[number, number]>,
  fillRgb: Rgb,
  pointSizePt: number,
): void {
  const fill = rgbToTikz(fillRgb);
  const r = pointSizePt.toFixed(3);
  for (const p of pts) {
    body.push('\\pgfinterruptpath');
    body.push(`\\fill[fill=${fill}] (${p[0].toFixed(2)},${p[1].toFixed(2)}) circle (${r}pt);`);
    body.push('\\endpgfinterruptpath');
  }
}

function subsampleIndices(length: number, max: number): number[] {
  if (length <= max) {
    return Array.from({ length }, (_, i) => i);
  }
  const out: number[] = [];
  const step = length / max;
  for (let i = 0; i < max; i += 1) {
    out.push(Math.min(length - 1, Math.floor(i * step)));
  }
  return out;
}

function seededRandom(seed: number): () => number {
  let state = seed >>> 0;
  return () => {
    state = (1664525 * state + 1013904223) >>> 0;
    return state / 0x100000000;
  };
}

function buildRandomIfsMatrices(config: { seed?: number; count?: number } = {}): Array<Record<string, number>> {
  const count = Math.max(3, Math.min(6, Math.round(config.count ?? 4)));
  const random = seededRandom(config.seed ?? 1337);
  const p = 1 / count;
  const matrices: Array<Record<string, number>> = [];
  for (let i = 0; i < count; i += 1) {
    matrices.push({
      a: random() * 0.62 - 0.31,
      b: random() * 0.62 - 0.31,
      c: random() * 0.62 - 0.31,
      d: random() * 0.62 - 0.31,
      e: random() * 2 - 1,
      f: random() * 2 - 1,
      p,
    });
  }
  return matrices;
}

/** Map fractal plane bounds to TikZ coordinates in [0, unit] x [0, unit * aspect], Y downward to match PNG. */
function buildTikzPixelMap(
  bounds: [number, number, number, number],
  pixelW: number,
  pixelH: number,
  padding: number,
): (x: number, y: number) => [number, number] {
  return createTransform(bounds, pixelW, pixelH, padding);
}

function wrapStandalone(tikzPicture: string, title: string): string {
  return [
    '% Generated by fractals-generator',
    `% ${escapeTikzComment(title)}`,
    '\\documentclass[tikz,border=2mm]{standalone}',
    '\\usepackage{tikz}',
    '\\begin{document}',
    tikzPicture,
    '\\end{document}',
    '',
  ].join('\n');
}

function exportIfsTikz(
  preset: AnyRecord,
  params: AnyRecord,
  scheme: string,
  bg: Rgb,
): string {
  const matrices = preset.randomGenerator ? buildRandomIfsMatrices(preset.randomGenerator) : preset.matrices;
  const fractal = new IFS({
    matrices,
    iterations: Number(params.ifsIterations ?? preset.defaults.iterations),
    density: Number(params.ifsDensity ?? preset.defaults.density),
    equation: preset.equation === 'radial' ? radial : undefined,
  });
  fractal.run();
  const pixelW = 1000;
  const spanX = Math.max(1e-9, fractal.bounds[0] - fractal.bounds[2]);
  const spanY = Math.max(1e-9, fractal.bounds[1] - fractal.bounds[3]);
  const pixelH = Math.max(1, Math.round((1000 * spanY) / spanX));
  const map = buildTikzPixelMap(fractal.bounds, pixelW, pixelH, 20);
  const pointSize = Math.max(0.25, Number(params.ifsPointSize ?? preset.defaults.pointSize ?? 1) * 0.35);
  const mode = String(params.ifsColor ?? preset.defaults.colorMode ?? scheme).toLowerCase();

  const byColor = new Map<string, Array<[number, number]>>();
  const idxs = subsampleIndices(fractal.points.length, MAX_IFS_POINTS_TEX);
  for (const i of idxs) {
    const [x, y, meta] = fractal.points[i];
    const [px, py] = map(x, y);
    const color: Rgb =
      mode === 'matrix'
        ? IFS_MATRIX_PALETTE[Math.abs(meta.matrixNum) % IFS_MATRIX_PALETTE.length]
        : gradientColor((Math.abs(meta.matrixNum) % 8) / 8, mode);
    const key = `${color[0]},${color[1]},${color[2]}`;
    let list = byColor.get(key);
    if (!list) {
      list = [];
      byColor.set(key, list);
    }
    list.push([px, py]);
  }

  const unit = '0.01cm'; // 1000 px => 10 cm
  const body: string[] = [];
  body.push(`\\begin{tikzpicture}[x=${unit},y=-${unit}]`);
  body.push(`\\fill[fill=${rgbToTikz(bg)}] (0,0) rectangle (${pixelW},${pixelH});`);
  for (const [key, pts] of byColor) {
    const [r, g, b] = key.split(',').map(Number) as Rgb;
    emitPointCircleFills(body, pts, [r, g, b], pointSize);
  }
  body.push('\\end{tikzpicture}');
  return body.join('\n');
}

function exportLsystemTikz(preset: AnyRecord, params: AnyRecord, scheme: string, bg: Rgb): string {
  const fractal = new LSystem({
    axiom: String(params.lsAxiom ?? preset.axiom),
    rules: parseRules(
      String(
        params.lsRules ??
          Object.entries(preset.rules ?? {})
            .map(([k, v]) => `${k}=${v}`)
            .join('\n'),
      ),
    ),
    iterations: Number(params.lsIterations ?? preset.defaults.iterations),
    distance: Number(params.lsDistance ?? preset.defaults.distance),
    angle: Number(params.lsAngle ?? preset.defaults.angle),
    lengthScale: Number(params.lsScale ?? preset.defaults.lengthScale ?? 1),
  });
  fractal.run();
  const pixelW = 1000;
  const lspanX = Math.max(1e-9, fractal.bounds[0] - fractal.bounds[2]);
  const lspanY = Math.max(1e-9, fractal.bounds[1] - fractal.bounds[3]);
  const pixelH = Math.max(1, Math.round((1000 * lspanY) / lspanX));
  const map = buildTikzPixelMap(fractal.bounds, pixelW, pixelH, 28);
  const lineWidth = Math.max(0.1, Number(params.lsLineWidth ?? preset.defaults.lineWidth ?? 1) * 0.35);
  const lineColor = parseColor(String(params.lsColor ?? preset.defaults.lineColor ?? ''), gradientColor(0.45, scheme));

  const unit = '0.01cm';
  const lines: string[] = [`\\begin{tikzpicture}[x=${unit},y=-${unit}]`];
  lines.push(`\\fill[fill=${rgbToTikz(bg)}] (0,0) rectangle (${pixelW},${pixelH});`);
  const drawPrefix = `\\draw[line width=${lineWidth.toFixed(3)}pt, draw=${rgbToTikz(lineColor)}] `;
  const flushPath = (path: string) => {
    if (path) lines.push(`${drawPrefix}${path};`);
  };

  let path = '';
  let prev: [number, number] | null = null;
  let firstCmd = true;
  for (const [x, y, meta] of fractal.points) {
    const current = map(x, y);
    if (!prev || !meta.paintable) {
      prev = current;
      continue;
    }
    const [x0, y0] = prev;
    const [x1, y1] = current;
    const segment = firstCmd
      ? `(${x0.toFixed(3)},${y0.toFixed(3)}) -- (${x1.toFixed(3)},${y1.toFixed(3)})`
      : ` -- (${x1.toFixed(3)},${y1.toFixed(3)})`;
    if (drawPrefix.length + path.length + segment.length > MAX_TEX_SOURCE_LINE_CHARS && path) {
      flushPath(path);
      path = `(${x0.toFixed(3)},${y0.toFixed(3)}) -- (${x1.toFixed(3)},${y1.toFixed(3)})`;
      firstCmd = false;
    } else if (firstCmd) {
      path = segment;
      firstCmd = false;
    } else {
      path += segment;
    }
    prev = current;
  }
  flushPath(path);
  lines.push('\\end{tikzpicture}');
  return lines.join('\n');
}

function imageToTikzRaster(
  image: Uint8ClampedArray,
  width: number,
  height: number,
  bg: Rgb,
  maxDots: number,
): string {
  const bgTol = 2;
  const nearBg = (r: number, g: number, b: number) =>
    Math.abs(r - bg[0]) <= bgTol && Math.abs(g - bg[1]) <= bgTol && Math.abs(b - bg[2]) <= bgTol;

  let step = 1;
  const est = width * height;
  if (est > maxDots) {
    step = Math.ceil(Math.sqrt(est / maxDots));
  }

  const unit = '0.01cm';
  const lines: string[] = [`\\begin{tikzpicture}[x=${unit},y=-${unit}]`];
  lines.push(`\\fill[fill=${rgbToTikz(bg)}] (0,0) rectangle (${width},${height});`);

  const buckets = new Map<string, Array<[number, number]>>();
  for (let y = 0; y < height; y += step) {
    for (let x = 0; x < width; x += step) {
      const i = (y * width + x) * 4;
      const r = image[i];
      const g = image[i + 1];
      const b = image[i + 2];
      if (nearBg(r, g, b)) continue;
      const key = `${r},${g},${b}`;
      let arr = buckets.get(key);
      if (!arr) {
        arr = [];
        buckets.set(key, arr);
      }
      arr.push([x + 0.5, y + 0.5]);
    }
  }

  for (const [key, pts] of buckets) {
    const [r, g, b] = key.split(',').map(Number) as Rgb;
    const dotSize = Math.max(0.25, step * 0.35);
    emitPointCircleFills(lines, pts, [r, g, b], dotSize);
  }
  lines.push('\\end{tikzpicture}');
  return lines.join('\n');
}

export type TexExportKind = 'tikz' | 'standalone';

export interface TexExportOptions {
  /** Max dimension for raster-based families (escape-time, Newton, attractor, inversion). */
  rasterMaxDim?: number;
}

function pickRasterSize(requestW: number, requestH: number, cap: number): { w: number; h: number } {
  const maxDim = Math.min(Math.max(requestW, requestH), cap);
  if (requestW >= requestH) {
    return {
      w: maxDim,
      h: Math.max(32, Math.round((maxDim * requestH) / requestW)),
    };
  }
  return {
    h: maxDim,
    w: Math.max(32, Math.round((maxDim * requestW) / requestH)),
  };
}

/**
 * Produce TikZ picture or standalone document for the given fractal state.
 */
export function exportFractalTex(
  family: FractalType,
  requestWidth: number,
  requestHeight: number,
  preset: AnyRecord,
  params: AnyRecord,
  mainColorScheme: string,
  backgroundColor: Rgb,
  kind: TexExportKind,
  options: TexExportOptions = {},
): string {
  const scheme = mainColorScheme.trim().toLowerCase() || 'acu';
  const cap = options.rasterMaxDim ?? DEFAULT_TEX_INTERNAL_RASTER;
  let tikz: string;
  let title = `${family} preset=${preset.label ?? ''}`;

  if (family === 'ifs') {
    tikz = exportIfsTikz(preset, params, scheme, backgroundColor);
  } else if (family === 'lsystem') {
    tikz = exportLsystemTikz(preset, params, scheme, backgroundColor);
  } else {
    const { w, h } = pickRasterSize(requestWidth, requestHeight, cap);
    const image = renderFractalImage(family, w, h, preset, params, scheme, backgroundColor);
    tikz = imageToTikzRaster(image, w, h, backgroundColor, MAX_RASTER_DOTS);
    title += ` (${w}x${h} raster)`;
  }

  if (kind === 'standalone') {
    return wrapStandalone(tikz, title);
  }
  return tikz;
}
