run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosec
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gofmt
    - goimports
    - misspell
    - goconst
    - gocritic
    - gofumpt

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gosec:
    severity: medium
  govet:
    check-shadowing: true
  unused:
    check-exported: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  # Exclude typecheck errors due to Go version mismatch with golangci-lint
  exclude-rules:
    - path: _test\.go
      linters:
        - typecheck
    # Exclude typecheck errors for progressbar (known issue with version mismatch)
    - text: "undefined: progressbar"
      linters:
        - typecheck
    # Exclude typecheck errors for sync/atomic (known issue with Go 1.24+)
    - text: "could not import sync/atomic"
      linters:
        - typecheck
